### ISSUE TITLE
Problem with read file

### ISSUE THREAD

**Issue by Ja-rek** [donnytian/Npoi.Mapper#48]
When I save the file everything work well, but when i want to read it I see:
``` csharp
System.MissingMethodException : No parameterless constructor defined for this object.
Stack Trace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at Npoi.Mapper.Mapper.Take[T](ISheet sheet, Int32 maxErrorRows, Func`1 objectInitializer)+MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
```
```csharp
var mapper = SummaryMapping.Mapper(PathHelper.directory + "/statement.xlsx");                                                                                                                                                                                  
var test = mapper.Take<SummaryExelPersistence>("sheet0").Count();
```

What can cause the issue?

**Comment by donnytian** [comment]
Hi, does `SummaryExelPersistence` has a parameterless constructor?
Otherwise you need provide a factory Func to the `Take` method.
